# Generated by Django 5.1.7 on 2025-05-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_age_profile_mbti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickame',
            new_name='nickname',
        ),
    ]
