# Generated by Django 5.1.7 on 2025-05-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weather',
            field=models.CharField(default='맑음', max_length=20),
        ),
    ]
