# Generated by Django 5.2.1 on 2025-05-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
